### ISSUE TITLE
Node v18 Support

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/statsd#5]
This app crashes on recent node versions. 

### Do This

Perhaps one of these:

* Fix bugs in this fork to work on node v18
* Run in docker on old node
* Pull in master from upstream and fix as needed

CC @mlahargou and @djmetzle

**Comment by djmetzle** [comment]
Looks like upstream Statsd has prebuilt docker images, and supports all version of Node:
https://github.com/statsd/statsd#installation-and-configuration

**Comment by danielbeardsley** [comment]
> Looks like upstream Statsd has prebuilt docker images, and supports all version of Node:

Agreed, but we have [several customizations](https://github.com/statsd/statsd/compare/master...iFixit:statsd:master) that would be a bigger job to port over or do without.

**Comment by mlahargou** [comment]
Just FYI, this is deprecated:
![image](https://user-images.githubusercontent.com/29667789/232146048-dece8249-ce2c-41a7-a7b4-e7aaf7854d75.png)

**Comment by danielbeardsley** [comment]
> Just FYI, this is deprecated

Agreed, which is why I removed it in the pull that closed this issue.
